version: '3'

services:
  server-bot:
    container_name: server-bot
    image: allenrkeen/server-bot:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #required
    env_file:
      - ./.env  #  environment:
