name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and Test
        run: |
          # Add commands to build and test here

      - name: Run tests
        run: |
          # Add commands to run tests here

      - name: Build and deploy
        run: |
          # Add commands to build and deploy here
